ALTER TABLE PostTag
DROP CONSTRAINT FK_PostTag_Post;

ALTER TABLE PostTag
ADD CONSTRAINT FK_PostTag_Post
	FOREIGN KEY (PostId)
	REFERENCES Post(Id)
	ON DELETE CASCADE;


ALTER TABLE AuthorTag
DROP CONSTRAINT FK_AuthorTag_Author ;

ALTER TABLE AuthorTag
ADD CONSTRAINT FK_AuthorTag_Author 
	FOREIGN KEY(AuthorId) 
	REFERENCES Author(Id)
	ON DELETE CASCADE;


ALTER TABLE BlogTag
DROP CONSTRAINT FK_BlogTag_Blog;

ALTER TABLE BlogTag
ADD CONSTRAINT FK_BlogTag_Blog 
	FOREIGN KEY(BlogId) 
	REFERENCES Blog(Id)
	ON DELETE CASCADE;


ALTER TABLE Post
DROP CONSTRAINT FK_Post_Author;

ALTER TABLE Post
ADD CONSTRAINT FK_Post_Author 
	FOREIGN KEY(AuthorId) 
	REFERENCES Author(Id)
	ON DELETE CASCADE;


ALTER TABLE Post
DROP CONSTRAINT FK_Post_Blog;

ALTER TABLE Post
ADD CONSTRAINT FK_Post_Blog 
	FOREIGN KEY(BlogId) 
	REFERENCES Blog(Id)
	ON DELETE CASCADE;


ALTER TABLE Note
DROP CONSTRAINT FK_Note_Posti;

ALTER TABLE Note
ADD CONSTRAINT FK_Note_Posti 
	FOREIGN KEY(PostId) 
	REFERENCES Post(Id)
	ON DELETE CASCADE;